/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x55, 0x53, 0xE7, 0xBC, 0x9D, 0x8E, 0x02, 0x7B}

#define DYNAMIC_KEYMAP_LAYER_COUNT 4
#define DYNAMIC_KEYMAP_MACRO_COUNT 4

#define LAYER_STATE_8BIT

/* top-left and bottom-right */
#define VIAL_UNLOCK_COMBO_ROWS { 0, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 11 }

#define RGB_MATRIX_FRAMEBUFFER_EFFECTS
#define RGB_MATRIX_KEYPRESSES

#define BACKLIGHT_BREATHING

#undef LOCKING_SUPPORT_ENABLE
#undef LOCKING_RESYNC_ENABLE

#define NO_MUSIC_MODE

// #define RGBLIGHT_ENABLE
// #define RGB_MATRIX_ENABLE
#define RGBLIGHT_DISABLE_KEYCODES
#define RGB_MATRIX_DISABLE_KEYCODES

#define MOUSE_JIGGLE_TIMEOUT_MS 60000  // 60 second timeout
#define MOUSE_JIGGLER_CPI 16000
