LTO_ENABLE = yes

# RGBLIGHT_ENABLE = yes
# RGB_MATRIX_ENABLE = yes

VIA_ENABLE = yes
VIAL_ENABLE = yes

TAP_DANCE_ENABLE = yes
SPACE_CADET_ENABLE = yes

COMBO_ENABLE = no
DYNAMIC_MACRO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
MAGIC_ENABLE = no
QMK_SETTINGS = no
MUSIC_ENABLE = no
